import EgldLogo from "assets/img/elrond-symbol.svg";

// mainnet
export const TOKENS = [
    {
        identifier: "EGLD",
        ticker: "EGLD",
        decimals: 18,
        url: EgldLogo,
        balance: 0,
        price: 1,
    },
    {
        identifier: "USDC-c76f1f",
        ticker: "USDC",
        decimals: 6,
        url: "https://media.elrond.com/tokens/asset/USDC-c76f1f/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "UTK-2f80e9",
        ticker: "UTK",
        decimals: 18,
        url: "https://media.elrond.com/tokens/asset/UTK-2f80e9/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "RIDE-7d18e9",
        ticker: "RIDE",
        decimals: 18,
        url: "https://media.elrond.com/tokens/asset/RIDE-7d18e9/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "BHAT-c1fde3",
        ticker: "BHAT",
        decimals: 18,
        url: "https://media.elrond.com/tokens/asset/BHAT-c1fde3/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "ZPAY-247875",
        ticker: "ZPAY",
        decimals: 18,
        url: "https://media.elrond.com/tokens/asset/ZPAY-247875/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "ITHEUM-df6f26",
        ticker: "ITHEUM",
        decimals: 18,
        url: "https://media.elrond.com/tokens/asset/ITHEUM-df6f26/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "AERO-458bbf",
        ticker: "AERO",
        decimals: 18,
        url: "https://media.elrond.com/tokens/asset/AERO-458bbf/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "PLATA-9ba6c3",
        ticker: "PLATA",
        decimals: 8,
        url: "https://media.elrond.com/tokens/asset/PLATA-9ba6c3/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "EFFORT-a13513",
        ticker: "EFFORT",
        decimals: 18,
        url: "https://media.elrond.com/tokens/asset/EFFORT-a13513/logo.svg",
        balance: 0,
        price: 1,
    },
    {
        identifier: "ISET-84e55e",
        ticker: "ISET",
        decimals: 6,
        url: "https://media.elrond.com/tokens/asset/ISET-84e55e/logo.svg",
        balance: 0,
        price: 1,
    }
];
